# Pramana — describe an experiment, run it, see the results

Pramana turns a plain-English description of a network experiment into a real,
measured run. You write **one sentence** describing what you want (the app, the
link speed, the latency, how long, and so on), and Pramana figures out the rest:
it configures the network, runs the application, captures the traffic, and records
the throughput and latency it actually measured.

**How to use this notebook:**

1. Edit the `INTENT` sentence in the next cell to describe your experiment.
2. Run the **Run experiment** cell and wait for the summary.
3. Run the **Show history** cell to see past experiments.

That's it, no network, API, or programming knowledge required.

In [57]:
from pramana_helpers import *  # loads the services and helper functions

# Describe your experiment in plain English:
INTENT = (
    "Run YouTube on a 6 Mbps bottleneck with 50 ms latency "
    "for 60 seconds using cubic congestion control and a pfifo queue."
)

# Optional — pin exact values by describing them in the sentence above.
# Examples you can write in plain English inside INTENT:
#   capacity:          "on a 10 Mbps link"
#   latency:           "with 20 ms latency"
#   congestion control:"using bbr"  (cubic / bbr / reno)
#   queue / AQM:       "with an fq_codel queue"  (pfifo / fq_codel / codel)
#   duration:          "for 90 seconds"
#   repeats:           "repeat 3 times"
#   concurrent apps:   "run YouTube and Zoom at the same time"

## Run experiment

In [58]:
run_and_display(INTENT)

Submitting intent to Pramana ...
  orchestration_id: orch-b6406d49
  running (shaping + capture + transfer can take a few minutes) ...
  pending ... (0s)
  executing ... (5s)
  complete ... (187s)

✓ Experiment complete
  App:        youtube
  Capacity:   6 Mbps
  Latency:    50 ms
  Throughput: 6.23 Mbps
  RTT:        299 ms

## Show history

In [59]:
show_history()

15 most recent experiment(s) in telemetry:

,when,app,status,capacity (Mbps),latency (ms),throughput (Mbps),rtt (ms)
0,2026-07-06 21:27:39,youtube,success,6,50,6.2343,298.976
1,2026-07-06 19:35:29,youtube,success,6,50,6.1445,282.828
2,2026-07-06 19:30:16,wget,success,10,20,10.3715,128.433
3,2026-07-06 19:08:36,youtube,success,6,50,6.1938,238.001
4,2026-07-06 19:04:34,youtube,success,6,50,6.1389,426.244
5,2026-07-02 20:41:14,wget,success,10,20,10.4316,14.288
6,2026-07-02 20:40:14,wget,success,10,20,10.4396,95.023
7,2026-07-02 20:38:14,wget,success,10,20,10.4474,109.021
8,2026-07-02 20:32:15,wget,success,10,20,10.452,110.873
9,2026-07-02 20:16:15,wget,success,10,20,10.438,104.981
10,2026-07-02 20:13:14,wget,success,10,20,10.436,103.023
11,2026-07-02 20:06:15,wget,success,10,20,n/a,n/a
12,2026-07-02 19:50:15,wget,success,10,20,n/a,n/a
13,2026-07-02 19:47:15,wget,success,10,20,n/a,n/a
14,2026-07-02 19:41:15,wget,success,10,20,n/a,n/a

,when,app,status,capacity (Mbps),latency (ms),throughput (Mbps),rtt (ms)
0,2026-07-06 21:27:39,youtube,success,6,50,6.2343,298.976
1,2026-07-06 19:35:29,youtube,success,6,50,6.1445,282.828
2,2026-07-06 19:30:16,wget,success,10,20,10.3715,128.433
3,2026-07-06 19:08:36,youtube,success,6,50,6.1938,238.001
4,2026-07-06 19:04:34,youtube,success,6,50,6.1389,426.244
5,2026-07-02 20:41:14,wget,success,10,20,10.4316,14.288
6,2026-07-02 20:40:14,wget,success,10,20,10.4396,95.023
7,2026-07-02 20:38:14,wget,success,10,20,10.4474,109.021
8,2026-07-02 20:32:15,wget,success,10,20,10.452,110.873
9,2026-07-02 20:16:15,wget,success,10,20,10.438,104.981
10,2026-07-02 20:13:14,wget,success,10,20,10.436,103.023
11,2026-07-02 20:06:15,wget,success,10,20,n/a,n/a
12,2026-07-02 19:50:15,wget,success,10,20,n/a,n/a
13,2026-07-02 19:47:15,wget,success,10,20,n/a,n/a
14,2026-07-02 19:41:15,wget,success,10,20,n/a,n/a